apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/demo
    repoURL: https://github.com/FantasmaMeoW/argo-helm-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true